export const ASK_QUESTION_REQUEST = "ASK_QUESTION_REQUEST";
export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS";
export const ASK_QUESTION_FAIL = "ASK_QUESTION_FAIL";

export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";

export const GET_QUESTIONS_DETAILS_REQUEST = "GET_QUESTIONS_DETAILS_REQUEST";
export const GET_QUESTIONS_DETAILS_SUCCESS = "GET_QUESTIONS_DETAILS_SUCCESS";
export const GET_QUESTIONS_DETAILS_FAIL = "GET_QUESTIONS_DETAILS_FAIL";

export const POST_ANSWER_REQUEST = "POST_ANSWER_REQUEST";
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS";
export const POST_ANSWER_FAIL = "POST_ANSWER_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";
export const DELETE_QUESTION_RESET = "DELETE_QUESTION_RESET";

export const DELETE_ANSWER_REQUEST = "DELETE_ANSWER_REQUEST";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";
export const DELETE_ANSWER_FAIL = "DELETE_ANSWER_FAIL";

export const VOTE_QUESTION_REQUEST = "VOTE_QUESTION_REQUEST";
export const VOTE_QUESTION_SUCCESS = "VOTE_QUESTION_SUCCESS";
export const VOTE_QUESTION_FAIL = "VOTE_QUESTION_FAIL";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";
export const UPDATE_QUESTION_RESET = "UPDATE_QUESTION_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
